### ISSUE TITLE
Non-existent parameter "gocardless_enterprise".

### ISSUE THREAD

**Issue by 84pixels** [Lendable/GocardlessEnterpriseBundle#1]
Hello,
Thank you for creating this bundle. I have problems to configure this bundle :

When i include new Gocardless\EnterpriseBundle\GocardlessEnterpriseBundle() on AppKernel.

ParameterNotFoundException in ParameterBag.php line 106: The service "gocardless_enterprise.client" has a dependency on a non-existent parameter "gocardless_enterprise".

Is there a documentation?

Thanks for you help!

**Comment by ppamment** [comment]
You need to create a parameter called gocardless_enterprise with your GoCardless configuration:

gocardless_enterprise:
    baseUrl: 'https://api.gocardless.com/'
    gocardlessVersion: '2015-04-29'
    webhook_secret: XXXXXXXXXXXXXXXXXXXXXX
    creditorId: XXXXXXXXXXXXXX
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXX

I am adding this to the readme now

**Comment by 84pixels** [comment]
Thank you for quick reply.

New error appear when i add gocardless_enterprise on config.xml :+1: 

>ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58: The service "gocardless_enterprise.client" has a dependency on a non-existent service "guzzle.client".

Gunzzle dependencies are installed.

**Comment by ppamment** [comment]
Hi,

Apologies, I assume you're the first people other than us to try using the bundle.
I've updated the composer json with the proper dependencies, try now with version 3.2

**Comment by 84pixels** [comment]
```
  - Installing misd/guzzle-bundle (v1.1.5)
    Downloading: 100%         

  - Removing lendable/gocardless-enterprise-bundle (3.1)
  - Installing lendable/gocardless-enterprise-bundle (3.2)
    Downloading: 100%         

  - Removing doctrine/doctrine-bundle (v1.5.1)
  - Installing doctrine/doctrine-bundle (v1.5.2)
    Downloading: 100%   
```

Same error with 3.2 version :+1: 
>ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58: The service "gocardless_enterprise.client" has a dependency on a non-existent service "guzzle.client".

**Comment by ppamment** [comment]
You need to add the misd/guzzle-bundle to your AppKernel or it won't be included in your project. Will update the readme

**Comment by 84pixels** [comment]
Hi,
Nice this run without errors!
Can you give me examples of GodcardlessBundle use?
For example add/remove customer, List customers.

Thanks for your help.

**Comment by ppamment** [comment]
I suggest you look at the Client class, it's fairly self explanatory and has methods named in an obvious way that do the things you want. Here is a class that would allow you to set up a customer and take payments:

```
use GoCardless\Enterprise\Client;
use Gocardless\EnterpriseBundle\Entity\Creditor;
use Gocardless\EnterpriseBundle\Entity\Customer;
use Gocardless\EnterpriseBundle\Entity\CustomerBankAccount;
use Gocardless\EnterpriseBundle\Entity\Mandate;
use Gocardless\EnterpriseBundle\Entity\Payment;

class Demo
{
    /**
     * @var Client
     */
    protected $goCardless;

    /**
     * @var string
     */
    protected $attachmentPath;

    public function __construct(Client $client, $attachmentPath)
    {
        $this->goCardless = $client;
        $this->attachmentPath = $attachmentPath;
    }

    /**
     * @param User $user
     *
     * @return Customer
     */
    public function createCustomer(User $user)
    {
        /** @var Address $address */
        $address = $user->getAddresses()->first();

        $customer = new Customer();
        $customer->setEmail($user->getEmail());
        $customer->setGivenName($user->getFirstName());
        $customer->setFamilyName($user->getLastName());
        $customer->setAddressLine1($address->getHouseNumber());
        $customer->setAddressLine2($address->getAddress());
        $customer->setAddressLine3($address->getAddress2());
        $customer->setCity($address->getTown());
        $customer->setPostalCode($address->getPostcode());
        $customer->setCountryCode('GB');

        return $this->goCardless->createCustomer($customer);
    }

    /**
     * @param User     $user
     * @param Customer $customer
     *
     * @return \GoCardless\EnterpriseBundle\Entity\CustomerBankAccount
     */
    public function makeCustomerBankAccount(User $user, Customer $customer)
    {
        if ((strlen($user->getFirstName()) + strlen($user->getLastName())) <= 17) {
            $name = $user->getFirstName().' '.$user->getLastName();
        } elseif (strlen($user->getLastName()) <= 16) {
            $name = substr($user->getFirstName(), 0, 1).' '.$user->getLastName();
        } else {
            $name = substr($user->getLastName(), 0, 18);
        }

        $account = new CustomerBankAccount();
        $account->setAccountHolderName($name);
        $account->setAccountNumber($user->getBankAccountNumber());
        $account->setBranchCode($user->getBankSortCode());
        $account->setCountryCode('GB');
        $account->setCustomer($customer);

        return $this->goCardless->createCustomerBankAccount($account);
    }

    /**
     * @param CustomerBankAccount $account
     * @param Creditor            $creditor
     *
     * @return \GoCardless\EnterpriseBundle\Entity\Mandate
     */
    public function makeMandate(CustomerBankAccount $account, Creditor $creditor)
    {
        $mandate = new Mandate();
        $mandate->setScheme('bacs');
        $mandate->setCustomerBankAccount($account);
        $mandate->setCreditor($creditor);

        $mandate = $this->goCardless->createMandate($mandate);
        /* @var Mandate $mandate */

        $path = sprintf('%s/mandates/%s.pdf', realpath($this->attachmentPath), $mandate->getReference());
        file_put_contents($path, $this->goCardless->getMandatePdf($mandate->getId()));
        $mandate->setPdfPath($path);

        return $mandate;
    }

    /**
     * @param Mandate $mandate
     * @param $amount
     * @param $description
     * @param array $metadata
     * @return \GoCardless\Enterprise\Model\Payment|Payment
     */
    public function createPayment(Mandate $mandate, $amount, $description, array $metadata = [])
    {
        $payment = new Payment();
        $payment->setAmount($amount * 100);
        $payment->setMandate($mandate);
        $payment->setDescription($description);
        $payment->setMetadata($metadata);
        $payment->setCurrency('GBP');
        
        $payment = $this->goCardless->createPayment($payment);
        
        return $payment;
    }
}
```

**Comment by 84pixels** [comment]
Hello,

I have problem when i want createCustomerBankAccount :

Client error response
>[status code] 422
[reason phrase] Unprocessable Entity
[url] https://api-sandbox.gocardless.com/customer_bank_accounts 


```
    public function indexAction()
    {

        $service = $this->get('gocardless_enterprise.client');
		
        $customer = new Customer();
        $customer->setEmail("paul".time().substr(uniqid(),0, 3)."@ananassurance.com");
        $customer->setGivenName("Paul");
        $customer->setFamilyName("Pamment");
        $customer->setAddressLine1("Flat 3G");
        $customer->setCity("London");
        $customer->setPostalCode("E2 8ET");
        $customer->setCountryCode("FR");

        $account = new CustomerBankAccount();
        $account->setAccountNumber("FR28 2004 1010 0821 4931 9F02 946");
        $account->setBranchCode("200000");
        $account->setCountryCode("GB");
        $account->setAccountHolderName("Mr P D Pamment");
        $account->setCustomer($customer);
        
        $mandate = new Mandate();
        $mandate->setScheme('bacs');
        $mandate->setCustomerBankAccount($account);         

        $customer = $service->createCustomer($customer);

        $account = $service->createCustomerBankAccount($account); 

        $mandate = $service->createMandate($mandate);   
               
        return $this->render('GocardlessBundle:Default:index.html.twig', array(
        'service' => $service,
        'customer' => $customer,
        'account' => $account,
        'mandate' => $mandate
        ));
    }

```

**Comment by ppamment** [comment]
Bank acccount numbers are 8 digits long. Please see the GoCardless documentation for validation they do on each field.
You can also call ->getReasonPhrase() on the exception for more info.

We are happy to help out with the bundle within reason, but for issues with the API itself you should really contact GoCardless.

**Comment by 84pixels** [comment]
Sorry!
Our Bundle compatible for french bank account? Or only UK ?

**Comment by ppamment** [comment]
We have not tested with French bank accounts as we only use it in the UK, but it should work as it is a generic imlementation,
I can see that we do not have the bank code on our model so great news if this fixes the problem. It would ideally be added to the underlying library:

https://github.com/Lendable/gocardless-enterprise

Could you possibly send a pull request? Thanks

**Comment by ppamment** [comment]
Thanks for the merge requests. One question though - do you not need to add the new fields to CustomerBankAccount as well as CreditorBankAccount?

**Comment by 84pixels** [comment]
I don't need to add new fields to CreditorBankAccount, i have only one creditor.

Have you an idea to check api and persist if payment failure ?
Ex :
- If customer payment denied, Send e-mail and persist to entity User. User = (FosUserBundle)
- If customer payment success, persist to entity User. User = (FosUserBundle)

**Comment by ppamment** [comment]
The merge request you just sent me added the fields to CreditorBankAccount:

https://github.com/Lendable/gocardless-enterprise/pull/3

**Comment by 84pixels** [comment]
Did you have create Webhook service to receive Gocardless events (https://developer.gocardless.com/pro/2015-07-06/#webhooks-overview) ?

**Comment by ppamment** [comment]
The client service has a validateWebhook method for checking the webhook is actually from GoCardless. In terms of what you want to do when different webhooks are received, that is really up to you to implement as it is custom business logic for your application.
