### ISSUE TITLE
Gocardless "2015-07-06"

### ISSUE THREAD

**Issue by 84pixels** [Lendable/GocardlessEnterpriseBundle#3]
Hello Lendable,

This is possible to use gocardlessVersion "2015-07-06" ?
Version "2015-04-29" not supported after january 2016.

Thanks :)

**Comment by ppamment** [comment]
Yes, It's on my to do list to upgrade

**Comment by titolendable** [comment]
I created a PR for it

**Comment by martin-georgiev** [comment]
Fixed with [v.3.2.3](https://github.com/Lendable/GocardlessEnterpriseBundle/releases/tag/3.2.3)
